### ISSUE TITLE
ImportError: cannot import name 'EvalResult' from 'pytorch_lightning' 

### ISSUE THREAD

**Issue by liuxianlin** [ws-choi/ISMIR2020_U_Nets_SVS#1]
**Hello, I encountered this error when configuring the environment. How can I solve it?**
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from source_separation.models.scripts import trainer, evaluator
  File "/home/Music/ISMIR2020_U_Nets_SVS-master/source_separation/models/scripts/trainer.py", line 8, in <module>
    from source_separation.models.model_definition import get_class_by_name
  File "/home/Music/ISMIR2020_U_Nets_SVS-master/source_separation/models/model_definition.py", line 3, in <module>
    from source_separation.models.tdc_net import TDC_NET_Framework
  File "/home/Music/ISMIR2020_U_Nets_SVS-master/source_separation/models/tdc_net.py", line 8, in <module>
    from source_separation.models.dense_u_net import Dense_UNET_Framework, Dense_UNET
  File "/home/Music/ISMIR2020_U_Nets_SVS-master/source_separation/models/dense_u_net.py", line 9, in <module>
    from source_separation.models.separation_framework import Spectrogram_based
  File "/home/Music/ISMIR2020_U_Nets_SVS-master/source_separation/models/separation_framework.py", line 12, in <module>
    from pytorch_lightning import EvalResult
ImportError: cannot import name 'EvalResult' from 'pytorch_lightning' (/opt/conda/lib/python3.7/site-packages/pytorch_lightning/__init__.py)

**Comment by ws-choi** [comment]
HI @liuxianlin 
It seems that the version of your pytorch_lightning is not 0.9.0.
Try reinstall pl like this

```python
pip install pytorch_lightning==0.9.0 
```

I'm sorry for the poor install instruction.

**Comment by liuxianlin** [comment]
thanks @ws-choi 
I got it.
